.TH NEXUSBFIX 1 "2025-02-09" "1.15" "USB Fix Utility Manual"
.SH NAME
nexusbfix \- USB Device Health Check & Auto-Fix Tool
.SH SYNOPSIS
.B nexusbfix
[\-\-dry\-run] [\-v | \-\-verbose] [\-y | \-\-yes]
.SH DESCRIPTION
Diagnoses and resolves common USB device issues on Linux systems.
.SH OPTIONS
.TP
\fB\-\-dry\-run\fR
Show actions without making changes
.TP
\fB\-v, \-\-verbose\fR
Show detailed output
.TP
\fB\-y, \-\-yes\fR
Auto-confirm all prompts
.SH AUTHOR
Arelius-D <arelius-d@outlook.com>
